site_name: Lumen
site_description: "Open-source agent framework for chatting with data and building dashboards"
site_author: "HoloViz Developers"
site_url: https://lumen.holoviz.org

repo_url: https://github.com/holoviz/lumen
repo_name: holoviz/lumen
edit_uri: edit/main/docs/
site_dir: builtdocs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.snippets:
      url_download: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            docstring_style: numpy
            show_if_no_docstring: true
            filters:
              - "!^_"

watch:
  - docs

nav:
  - Home: index.md
  - Installation: installation.md
  - FAQ: faq.md

  - Getting Started:
    - Launching Lumen: getting_started/launching_lumen.md
    - Navigating the UI: getting_started/navigating_the_ui.md
    - Using Lumen AI: getting_started/using_lumen_ai.md

  - Tutorials:
    - Weather Data Explorer: tutorials/weather_sounding.md

  - Configuration:
    - CLI: configuration/cli.md
    - Prompts: configuration/prompts.md
    - Data Sources: configuration/sources.md
    - LLM Providers: configuration/llm_providers.md
    - Agents: configuration/agents.md
    - Tools: configuration/tools.md
    - Analyses: configuration/analyses.md
    - Coordinator: configuration/coordinators.md
    - Specs:
      - Index: configuration/spec/index.md
      - Build a Dashboard: configuration/spec/build_dashboard.md
      - Core Concepts: configuration/spec/core_concepts.md
      - Pipelines: configuration/spec/pipelines.md
      - Architecture: configuration/spec/lumen_architecture.md
      - Caching: configuration/spec/cache.md
      - Files: configuration/spec/files.md
      - Branching Pipelines: configuration/spec/branch_pipeline.md
      - Python Pipelines: configuration/spec/pipeline_python.md
      - Python Dashboards: configuration/spec/dashboard_python.md
      - Deployment: configuration/spec/deploy.md
      - Views: configuration/spec/views.md
      - Validate Specs: configuration/spec/validate.md
      - Download Data: configuration/spec/download_data.md
      - Authentication: configuration/spec/auth.md
      - Callbacks: configuration/spec/callbacks.md
      - Local Components: configuration/spec/local_components.md
      - Variables & References: configuration/spec/variables_and_references.md

  - Reference:
    - API: reference/api/
    - Contributing: reference/contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/holoviz/lumen
    - icon: fontawesome/brands/discourse
      link: https://discourse.holoviz.org/c/lumen/
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/rb6gPXbdAr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/holoviz_org
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lumen/

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js
